### ISSUE TITLE
For languagetool 4.8, need to remove trailing slash from 

### ISSUE THREAD

**Issue by inspire22** [wikiti/languagetool-ruby#1]
The readme has:

`api = LanguageTool::API.new base_uri: 'http://localhost:8081/v2/'`

But it needs to be:

`api = LanguageTool::API.new base_uri: 'http://localhost:8081/v2'`

Thanks for making this project!

**Comment by wikiti** [comment]
Hey @inspire22 ,

Thank you for pointing that out. I've updated the README.md file.

Best regards,
Daniel
